version: '3'

services:

    dachs:
        container_name: dachs_${TAG}
        build: ./dachs
        tty: true
        network_mode: 'bridge'
        ports:
            - '${DACHS_PORT}:80'
        volumes:
            - dachs_data:/var/gavo
            - ${SERVICE_PATH}:/services
            # TODO: only /var/gavo/logs/web.log is required no?
        links:
            - postgres
        depends_on:
            - postgres
        # TODO: copy observatory logo, cf. https://voparis-confluence.obspm.fr/pages/viewpage.action?pageId=560675
        # TODO: Add all other DaCHS parameters in .env (such as OV name, etc.)

    postgres:
        container_name: postgres_${TAG}
        build: ./postgres
        tty: true
        network_mode: 'bridge'
        ports:
            - '${PSQL_PORT}:5432'
        volumes:
            # TODO: do not use 9.4 here (there is a ENV for psql version in the DaCHS Dockerfile), instead create a symlink in the dockerfile.
            - postgres_data:/var/lib/postgresql/9.4/main

    awstats:
        container_name: awstats_${TAG}
        build: ./awstats
        environment:
            - SERVERNAME=${SERVERNAME}
            - DOMAIN=${DOMAIN}
        tty: true
        network_mode: 'bridge'
        ports:
            - '${AWSTATS_PORT}:80'
        volumes:
            - dachs_data:/var/gavo
            # TODO: only /var/gavo/logs/web.log is required no?
            # TODO can we instead use something like volume-from dachs?
        depends_on:
            - dachs
        command:
            - ${CRONTAB} # The crontab config

# TODO: name volumes for prod and test: http://stackoverflow.com/questions/42952855/env-file-named-volume-in-docker-compose
volumes:
    postgres_data:
    dachs_data:
